// <auto-generated />
using BookStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStore.Migrations
{
    [DbContext(typeof(AppDatabaseContext))]
    partial class AppDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.6.23329.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookStore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Non-Fiction"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Name = "History"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 11,
                            Name = "Self-Help"
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 12,
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 13,
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 14,
                            Name = "Humor"
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = 15,
                            Name = "Children"
                        },
                        new
                        {
                            Id = 16,
                            DisplayOrder = 16,
                            Name = "Religion"
                        },
                        new
                        {
                            Id = 17,
                            DisplayOrder = 17,
                            Name = "Science"
                        },
                        new
                        {
                            Id = 18,
                            DisplayOrder = 18,
                            Name = "Math"
                        },
                        new
                        {
                            Id = 19,
                            DisplayOrder = 19,
                            Name = "Poetry"
                        },
                        new
                        {
                            Id = 20,
                            DisplayOrder = 20,
                            Name = "Art"
                        },
                        new
                        {
                            Id = 21,
                            DisplayOrder = 21,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 22,
                            DisplayOrder = 22,
                            Name = "Comics"
                        },
                        new
                        {
                            Id = 23,
                            DisplayOrder = 23,
                            Name = "Graphic Novels"
                        },
                        new
                        {
                            Id = 24,
                            DisplayOrder = 24,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 25,
                            DisplayOrder = 25,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 26,
                            DisplayOrder = 26,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 27,
                            DisplayOrder = 27,
                            Name = "Classics"
                        },
                        new
                        {
                            Id = 28,
                            DisplayOrder = 28,
                            Name = "Crime"
                        },
                        new
                        {
                            Id = 29,
                            DisplayOrder = 29,
                            Name = "Detective"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
